language: python
dist: xenial
sudo: true
python:
  - "3.7"
# Install dependencies
install:
  - pip install -r requirements.txt

# Run tests
script:
  - pytest

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: RackReaver
  password:
    secure: "dEvUCfqS/e66WdDUcUZtfzL8rebhsTH2esOJTuLstnN6bp0ugAXg5UJSUNSDdBC6QSItFcidwTGHbgpEbQ1qS30rKnTClbEZp0bh7XT0FjCBnJhKu+/NqDDZ2krJEIzI0ZHD2r1PeXBu7AjJQRrVpbGRtzsNkkOB7S58aG5m9cSD+E6fGwE+pz0WfbYRrc3xVDVS4asIaNucfwYBnTSa3V28dqO6nlGgkqYUi9pMXyOvmLpT/1QHOBxtI2ll6YLVcGyNESbA21lk4ApwYEb/9s0fmQhc9aLYvLDJvqnGf+64Qj0qbKiYY2L5gnhRpsl+O7RmGG5JJKEchp58AkJJOqt5mfUKT4vhMC5NS/zfa6mYNab1jVc9YnJ0ZqU5HBxuqHzwv9VC+7A1x2VESPKScVxlTy7EcxLzWYTwtTcEnXkg9MXrDEAm9mTKvc5ExHv0rtt6sLxpM+WirHCB35oaG0TOsNG2neJRx2EnIrgBCoyn/8XUOgw7LxmyRIWIIx/K26L/V/B77EPH9OMXcFBRB8hWUH7nQLZz+WIG0rGy/OYslOJS0RXJYQaEycrSfNovEazQUu8Yb/hsHMe3V7jHxPNqJ4JEqIQ4TgvO9/V+DP/X8w7S7G7mAaiHYRhK4AnohmryiJEpFxZHnQ2DlWvX4HzUwpSzPj7YKfBv3MxyIuE="
  on:
    tags: true